### ISSUE TITLE
Amplifier: Sound volume zero (0) does not give complete silence

### ISSUE THREAD

**Issue by phoboz** [jotego/jt12#21]
I tried to mute the sound completely in order to get rid of the clicking/popping sounds while in reset by setting the amplifier volume to zero. However I noticed that zero volume to the amplifier does not give me complete silence.

**Comment by jotego** [comment]
That clicking sound is related to a change I made to the keyon implementation last week. After revieweing all the posts in the spritesmind thread, I have come to a conclusion that I need a totally different keyon scheme. I think the clicking will go away naturally with the new scheme.

**Comment by jotego** [comment]
This is fixed now.
