### ISSUE TITLE
Thunder Force IV

### ISSUE THREAD

**Issue by jotego** [jotego/jt12#23]
ingame music stalls until the player's ship fires. Then music seems to be playing at the shooting pace.

**Comment by jotego** [comment]
This is confirmed to happen on MisTER too with corrected CPU interface (no synchronizers)

**Comment by sorgelig** [comment]
I would correct it: it plays music only when FX sounds played. You don't need to press the fire. If there some crashing or exploring sound, then music will also play.
Just to be clear: it's not related to input events.

**Comment by jotego** [comment]
Corrected with sorgelig timer fix.
The problem was that "LOAD" signal need be clear after each MMR write cycle. That is why it is common to see software clearing the flag and loading the timer in the same instruction.
Changes are still not applied to the master branch.

**Comment by sorgelig** [comment]
While debugging the app (vdpdoc.bin) i discovered it sends 0x1F to timer flag regs every time timer_A overflows and at the same time wait for timer_B overflow. And with old behavior timer_B would never  overflow as timer_A has shorter time and 1F reloads both timers.

**Comment by jotego** [comment]
So the problem is the the **load** operation should not re-start the counter then?

**Comment by sorgelig** [comment]
right. So now it's constantly reloading when load=0, and when load switch to 1, timer counter already has last loaded value.
