### ISSUE TITLE
Megadrive games with sound issues

### ISSUE THREAD

**Issue by jotego** [jotego/jt12#25]
-Worms
-Double Dragon II
-Demo Titan Overdrive2 (may not work on MiST port of fpgagen)

**Comment by gyurco** [comment]
Titan Overdriver 2 works on MiST, too, just no music.

**Comment by ElectronAsh** [comment]
Hi, jotego. ;)

I think I might have just found the main cause of the strange sound in things like the "rings" sound effect in Sonic 2, where the second and third notes play at a much lower pitch...

I recently spent some time getting Verilator to work for various projects, and it's great.

So, I "compiled" the latest jt12 core with it as well, then ran a simulation where I wrote various values to the YM from the C code.

I just used the fixed values that I took from the Exodus emulator for the "rings" sound effect, and messed around until I narrowed down the problem.

The second of the three-note sound effect has these values...

freq = 0x3C5;
block = 5;

I found that if I set the frequency to 0x38E, it still sounded OK, but when I tried a value of 0x38F, then it started sounding weird until the pitch changed far more.

I knew that the "block" bits formed the upper bits of the frequency on the YM, so assumed a value was probably wrapping somewhere.

Anyway, long story short, in jt12_pg.v...

//reg [16:0] phinc_VI;
reg [20:0] phinc_VI;	// FIX, by ElectronAsh 6-10-18...
// phinc_V is 17 bits, so has a max value of 131,071.
// mul_V is 4 bits, so has a max value of 15.
// If you multiply those together, it requires that phinc_VI is a 21-bit register for storing the result!
// (may need other logic changing which uses "phinc_VI", but seems to work OK for now.)

Finally, the infamous "rings" sound effect seems correct now, and it doesn't appeared to have broken anything else, at least on Sonic 2.

I don't know what else my "fix" might break, but yeah.

With you core, and Alexey's recent fixes to Torlus' Genesis core, it's now one of the best on the MiSTer platform. ;)

Thanks for your work on this core. It only seems to require around 752 ALMs on the Cyclone V, which is roughly around 2,000 LEs, so FAR more compact than the older YM core.

Regards,
ElectronAsh.

**Comment by jotego** [comment]
Hi ElectronAsh,

I am very grateful for your input. It all makes sense except that I think I had evidence that real hardware used 20 bits for the phase increment register. So I have increased phinc_VI to 20-bit and will try with that value. On the next pipeline stage the value goes into phase_in, which is a 20-bit register, so probably the synthesizer is cutting phinc_VI to 20-bit anyway.
I have the code broken right now as I am adding the clock enabler feature that Alexey asked for so I cannot test this right away. If you have it handy and can try with phinc_VI as a 20-bit register that will be helpful.

Again, I know how hard it is to set up the verilator simulation for this and debug the code. Thank you so much for this. This is exactly what open source is about.
Regards,
jotego

**Comment by ElectronAsh** [comment]
Hi,

Yep, no problem. Just re-compiling now with phinc_VI as 20-bit.

I did notice that it goes to phase_in and phase_drop as well after that, so wondering if it still works OK.

The max value for phase_VI would still need 21 bits, though, so I'm not sure how to handle that, but then any notes are probably unlikely to go that high in frequency anyway?

I may be misunderstanding the phase gen though. The upper bits of (phase_in[19:10]) basically just drives the FM sine ROM stuff, yes?

So, the other wider phase register before that hold a fixed-point value, with bits [9:0] being the fraction?

(and the upper bits of the result obviously just increment at a certain rate, over multiple clock cycles until the lower fraction bits overflow?)

I will upload the Verilator source soon, btw. I'm not an amazing C/C++ coder by any means, but I did manage to get it to play the audio directly, using OpenAL. ;)

(it does have to buffer for a few seconds, as I haven't worked out how to stream audio yet, but it's still handy.)

Actually, here's my rough code for Verilator as it is now...

https://paste.ofcode.org/BfNtTbe9A75FXPPuKRsZEU

I then just have this shell script (in Ubuntu, on a VM, on Win 10) along with your jt12 core files...

verilator  -Mdir out -Wall -Wno-lint -Wno-COMBDLY -Wno-INITIALDLY -Wno-UNOPTFLAT -LDFLAGS -lopenal --cc jt12.v --exe sim_main.cpp

I had to do an apt-get for OpenAL, of course, but then it worked OK.

(don't know why I have -Wall in there. I should get rid of that.)

I kept manually messing with the values being written to the jt12 core, recompile, then see what it sounded like. I had a hunch it was probably a value wrapping around or something, then eventually found that phase_VI thing. ;)

I don't know if my "code" is good enough to upload to my own github yet, as it's a bit of a mess. lol

There are still some slight issues with the sound on the Genesis core atm, but yourself, Alexey, and others have done a lot to get this far, and it's sounding pretty great now.


Might be a good coding exercise for me to try getting a VGM player working with the jt12 core.


Regards,
ElectronAsh.

**Comment by sorgelig** [comment]
Sorry for may be unrelated topic, but i want to talk about volume of FM.
It very very very very low.. Even with pretty strong compressor i've applied on output, the volume is still very low comparing to other cores. When i mix PSG output with FM, i have to divide PSG volume to 16(!) to make equal output volumes.
This is really big problem with FM and need to be solved. Maybe wave forms can have less dynamic range so mixing won't affect so much on resulted volume.
When core is loaded the analog output has "boom" at start. So this boom is several times stronger than any sound i can hear from games.

**Comment by ElectronAsh** [comment]
One very minor thing I noticed when "compiling" jt12 using Verilator - it complained a lot about the use of non-blocking assignments within always@(*) blocks.

I don't think that should make much difference in most cases, as long as Quartus will compile it, and that the results of the assignments don't depend on the previous results in the same or other blocks?

Just thought I'd mention it, in case it wasn't intended, but I doubt it makes a difference. ;)

**Comment by jotego** [comment]
Any non-block assignment i.e. a <= inside a logic block is a typo and I should correct it. One great thing of Verilator is how it reports a lot of useful warnings. I should set it up for this project too.

**Comment by ElectronAsh** [comment]
I found Verilator super useful for those warnings, too.

It helped me find lots of mistakes in my own code / logic.

I managed to get it simulating my kludge of an SGI Indy core recently, including dumping of the VGA output to a file. I was amazed that worked first time, as I just dumped the video data into a raw file, then opened it in Paint Shop Pro with the values for total pixels / total lines. lol

I also got Torlus' Atari Jaguar core running in Verilator...
 
![snapshot0017](https://user-images.githubusercontent.com/24658385/46580635-88577f80-ca20-11e8-89a2-390f8b9021c9.png)

(although, it took about 8 seconds of realtime just to simulate 1 millisecond of the Jaguar core on my Core i7. Might be best to use it only for parts of the core, tbh.)

Would be amazing to get that core running on MiSTer soon. I also still need to figure out how to get a template project working, which just loads ROMs into SDRAM or DDR3.

I tried that for my MIDI synth a while back (to add it alongside the ao486), but I didn't manage to read the correct data from RAM on the FPGA side for some reason.

I can now see SO much potential in Verilator. I will be using it to work on my SNES core again very soon.

**Comment by sorgelig** [comment]
I don't care about MiSTer advertisements as i don't sell it.

By the way, i cannot find info about writing to 8bit Sega ports (like FM and PSG) if writing is 16bit value  to even address. Genesis has ASIC chip which makes 16bit address for 8bit Z80 area, but it's unclear what happens if both UDSn and LDSn will be active. What A0 value in Z80 address space will be set by that ASIC chip?

**Comment by ElectronAsh** [comment]
I'm not 100% sure, but I think in most cases, the 68000 code will only write to word-aligned addresses anyway?

It might not always be the case, but this seems to happen quite often on the Sega 68000 stuff when it's writing to an 8-bit device.

I guess in most cases, they will just hook up the address lines from the 68000 (say A[8:1]) to pins A[7:0] on the 8-bit chip, so the reads and writes will need to be word-aligned on the 68000 anyway?

Then I guess usually the lower byte of the 68K addr bus just routed directly, and LDSn checked for Writes?

**Comment by sorgelig** [comment]
68000 has no A0 line at all. So, there is no such thing as word aligned write.
Genesis core has check for UDSn/LDSn and route either high or low byte to 8bit port. I'm not sure if this check is correct, but FM has A[1:0] lines and official addresses A04000-A04003 thus upper byte has to be routed to 8bit port, thus UDSn/LDSn are used to make A0 line.

So, original question about UDSn/LDSn priority is still legit.

**Comment by jotego** [comment]
> Sorry for may be unrelated topic, but i want to talk about volume of FM.
> It very very very very low.. Even with pretty strong compressor i've applied on output, the volume is still very low comparing to other cores. When i mix PSG output with FM, i have to divide PSG volume to 16(!) to make equal output volumes.
> This is really big problem with FM and need to be solved. Maybe wave forms can have less dynamic range so mixing won't affect so much on resulted volume.
> When core is loaded the analog output has "boom" at start. So this boom is several times stronger than any sound i can hear from games.

The sheer amount of channels to mix makes volume low if saturation is to be prevented. Original hardware did not feature compression but plain amplification. This can be done as post processing with a limiter amplification module. I prefer that solution to compression as it is closer to original hardware. Anyway, if you want to talk about this, I'll open a different issue for it.

**Comment by sorgelig** [comment]
Ok. let's open different issue for volume issue.

**Comment by sorgelig** [comment]
This simple VDP sample app also has no sound: http://md.squee.co/File:InteractiveVDPDocs.zip
May be it will help to trackdown the source of problem.

Unfortunately it has no source code :(

**Comment by jotego** [comment]
There is still some debate about the phase increment calculation. Version 0.4 has now a limiter, but there is still some hiss in the sound for Streets of Rage 2.

**Comment by sorgelig** [comment]
Turrican has buggy music. 
The first and easy to reproduce problem is pause the game - it will play a single tone instead to be muted.

**Comment by jotego** [comment]
Turrican is fixed now on version 0.5. Closing this issue.
