### ISSUE TITLE
Add ladder effect 

### ISSUE THREAD

**Issue by jotego** [jotego/jt12#44]
Done in the MiSTer fork already. Update this repo. [MiSTer commit with the change. ](https://github.com/MiSTer-devel/Genesis_MiSTer/commit/195d16cad5e1a708a27fc0323531b2e4c7482f0d)

**Comment by birdybro** [comment]
Can this issue be reopened? Currently the core behaves as a ym3438 not a ym2612 until the ladder effect is implemented. It will also benefit a potential FM Towns core in the future, as that is the other system that used a ym2612 with the same effect. Here is how it was modified previously by @Kitrinx, for reference. --> https://github.com/MiSTer-devel/Genesis_MiSTer/commit/195d16cad5e1a708a27fc0323531b2e4c7482f0d

Thank you! :)

If the ladder effect is already implemented, can you give me a hint on how to enable it for use in the genesis core?

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/Genesis_MiSTer/compare/master...birdybro:jt12_attempt3 - I've almost got it figured out I think.
