### ISSUE TITLE
Channel issue with Neo Geo jingle

### ISSUE THREAD

**Issue by retrorepair** [jotego/jt12#57]
Me again 🙈

So I've downloaded the latest Winamp and in_vgm plugin to see what's going on here and I've isolated all the channels. I've found that actually, with the Art of Fighting Neo Geo jingle, PSG isn't used at all.

The problem seems to be that FM channel 3 isn't playing anything. It should play the same notes as channel 2 just slightly pitched down to give that "chorus" effect I was talking about.

Does this mean FM channel 3 isn't working at all or just in Neo Geo? I'm certain this is the issue now.

I will upload some examples if I can when I'm at my laptop again.

**Comment by retrorepair** [comment]
Attached is a WAV file with two examples, first with channel 2 and 3 isolated, the second with just channel 2 isolated. The latter is how I believe this sounds in JT12 at the moment.
[NeoGeo_FM2_FM3.zip](https://github.com/jotego/jt12/files/4775162/NeoGeo_FM2_FM3.zip)

**Comment by jotego** [comment]
I can now hear the difference you had realised of. I don't think there is any channel missing but that something is not playing right. Maybe some operator configuration is wrong. Could you produce a wav file for each isolated channel? I'll do the same here so we can isolate which channel is wrong.

**Comment by retrorepair** [comment]
Ok so attached is a WAV with four samples, only four channels are used in the jingle so I'm not sure if other channels will be affected by this.

First is channel 2, then 3, then 5, then 6.
[NeoGeo_FM2_FM3_FM5_FM6.zip](https://github.com/jotego/jt12/files/4776115/NeoGeo_FM2_FM3_FM5_FM6.zip)

**Comment by jotego** [comment]
Thank you. I'll them now. 
I attach here all six FM channels as an Audacity project file. Please compare them with yours too. Channel naming for this chip actually goes like 0,1,2 and 4,5,6 so I guess when you say "CH2" it means channel 1 internally.

[neogeo-logo-audacity.zip](https://github.com/jotego/jt12/files/4776129/neogeo-logo-audacity.zip)

**Comment by retrorepair** [comment]
Sorry yes I meant to point out channel numbering on the plugin begins at 1.

It looks to me like actually, channel 2 (on your Audacity project) is present but not correct. It's like it's selected the wrong "instrument". 

Oddly enough, it seems to have done this with channel 6 too. I wonder has every other channel got this issue? I'm sure it's not selected the wrong instrument, more it's applying the wrong carrier waveform.

I wish I remember enough from my days programming FM synths to say correctly what it's doing, but you can probably tell from both of our examples.

In essence, 1 and 2 should sound the same and so should 5 and 6.

**Comment by jotego** [comment]
I think I've found the problem. Please let me know what you think of the attached file first, before going into more details.

[neogeo-fix.zip](https://github.com/jotego/jt12/files/4779850/neogeo-fix.zip)

**Comment by retrorepair** [comment]
It's hard to tell with 5 and 6 but 1 and 2 sound perfect now :)

**Comment by jotego** [comment]
I was using one time slot of channels 2 and 6 to accumulate ADPCM data but that must have been some misunderstanding. It is channels 0 and 4 that are free for YM2610. So ADPCM data is accumulated during those slots now. While ADPCM data is accumulated, the FM data is ignored, that's why we were missing one operator output for those two channels.
This would have affected all games using some specific configurations on those two channels. Not so easy to spot in real life, so I am really thankful for your pointing at it.
I close this now and I'll let MiSTer devel guys know about it.

**Comment by retrorepair** [comment]
Excellent, glad I could help :)

Does this affect Genesis too?

**Comment by jotego** [comment]
No. This is specific to a YM2610 related file. YM2203 and YM2612 modes were not affected.
