### ISSUE TITLE
Genesis with current master

### ISSUE THREAD

**Issue by gyurco** [jotego/jt12#58]
I've found out that this patch:
https://github.com/MiSTer-devel/Genesis_MiSTer/commit/2db31a0f8350aed6101afda307c792e7c2be580c
is needed to current master to work with Genesis (just listen Titan2).

**Comment by jotego** [comment]
I have replicated it and committed the change.

https://github.com/jotego/jt12/commit/56ee1717e261271bb010be52daadeed345bf9ac9

Thank you!
