### ISSUE TITLE
Sound issue in Neo geo core

### ISSUE THREAD

**Issue by thehughhefner** [jotego/jt12#59]
Hi Jotego,
It has come to my notice that the JT12 is used in the Neo geo core for the MiSTer and me including other people have noticed some issues with the sound. I believe this has been reported before but not sure what was concluded. It is something with the PCM and the pitch that is not correct. 

Kind regards

**Comment by thehughhefner** [comment]
There are some comments regarding this in the MiSTer discord server from a couple of users.

**Comment by darkphoenixfox** [comment]
This is very obvious during the Pulstar opening. It does not happen in the music test when playing the same BGM.

**Comment by Toryalai1** [comment]
I thought there was another thread regarding this in the neo geo repo.

**Comment by jotego** [comment]
The sound problem in the NeoGeo core is due to the design of that core, and not to JT12. Sometimes it is not the guitar, but the player ;-)
