### ISSUE TITLE
ADPCMB end address check should be not equal

### ISSUE THREAD

**Issue by greyrogue** [jotego/jt12#60]
According to MAME, the end address comparison should be != instead of <.  I think that means if end is less than start, it wraps:
https://github.com/Rakashazi/emu-ex-plus-alpha/blob/master/NEO.emu/src/gngeo/ym2610/ym2610.c#L2710
-Required for World Heroes Perfect guitar sample on ADPCMB (Jukebox = 0xFC25).

I didn't realize there appear to be some changes made to MiSTer where it's out of sync with this master version related to start/stop samples:
See the commits from Nov 11,2019 and Aug 27,2019.
Like this issue, I think I sourced those changes from MAME, but I don't know if they're accurate to hardware.

**Comment by jotego** [comment]
Thank you. I have just copied the whole adpcm folder from MiSTer. It looks like the ports of the top ADPCM module had not been changed so it should be ok. I don't have any other arcade core at the moment that uses the JT10 features to test it on. Only NeoGeo.
