### ISSUE TITLE
Genesis Regression: Bimini Run audio playing too fast

### ISSUE THREAD

**Issue by birdybro** [jotego/jt12#62]
https://github.com/MiSTer-devel/Genesis_MiSTer/issues/26#issuecomment-1117934103 - as confirmed by gyurco, Bimini Run has a regression that points to this commit --> https://github.com/jotego/jt12/commit/66eb9ee162e1b1cd3f31f7549af969c7bc191951

**Comment by jotego** [comment]
Closed in 6d51e0b thanks to Gyurco.

**Comment by birdybro** [comment]
Thanks!

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/Genesis_MiSTer/pull/211 - cross-ref
